### ISSUE TITLE
repo has no license

### ISSUE THREAD

**Issue by declann** [mine-cetinkaya-rundel/ld-dashboard#2]
Hi, this dashboard example is interesting.
I'm considering to fork but simulate and present data using [calculang](https://calculang.dev).
If this is reasonable would you be able to clarify a license in the repo? :grinning:

**Comment by mine-cetinkaya-rundel** [comment]
Just added a license! https://github.com/mine-cetinkaya-rundel/ld-dashboard/blob/main/LICENSE.md

**Comment by declann** [comment]
Thanks Mine!
